language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: j3vQgjG6I8CrWMn/5rNrjvtCJhcN0/4iukOo1QcPPxWDzCnm+OxgI+vsGmoskbS9INxgxm+n8sqHr9LjA+6xzEnsJ7cWI3MZTJ7VIWdpnlJRF0VLmyVxyqB8ZPiuBLy520FGSLf6SZy7y9DkPhCJ/b83TAVPgNMigc41yS756wLYxQi6MI6oTyo7SLWfgsCP5cbz7b/uLU5/rfi0dqNd3Z0ONwGyMe3a60SynWsDBQg73YCt0Up035DxoxMRdGD+TvAPnrfW8iZ2c3kEr/DB2XSKr5bVMfv6WtLVTKVBcAxM0lMlYRKDma6LllJ/9J4IJgacnChxeds6tl9TaXz1jvGAqmz1BW2ZiLRj48y2f+aOehrsx3DYL1zsuNsJ6AFk7mPbUi4suq9+L196AQJ02iMjOEheXHQs6iORSvz055bxyTl4FCjCd2O2qN32i7HbjHDvTQkWTLGl/Sn+M+W9yWTPx6IZx2kJZxSjz31m8FAGeEgZnLpJFsx9PLZxP5mx7rikDDMBIxRY8ROQTFBc+FCo0433InoLdNJnltlSVQtBC3XHCRmVh3Vce2BpFQR539Cmc7mIqN8aOeA2+ybCSGuXPxz9NE5pFoETyMdSEl8bHkCvMIBKnj92E7F83OzMHUblhyv3Lv71oPmxCN0Zv2AyHtqAszP5KcfU9Lb8l9o=
